### ISSUE TITLE
Problem with your adapter it doesnt work. [German/English]

### ISSUE THREAD

**Issue by eXplOiD1** [DeadBoolean/ioBroker.zoneminder#4]
host.homeserver | 2017-12-12 17:34:35.023 | error | instance system.adapter.zoneminder.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at endReadableNT (_stream_readable.js:1056:12)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at IncomingMessage.emit (events.js:207:7)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at emitNone (events.js:110:20)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at IncomingMessage. (/mnt/iobroker/node_modules/iobroker.zoneminder/zoneminder.js:67:51)
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]:     at JSON.parse ()
Caught | 2017-12-12 17:34:35.023 | error | by controller[0]: SyntaxError: Unexpected token < in JSON at position 0

**Comment by DeadBoolean** [comment]
Please post the apache error.log.
Which OS, Node.js, PHP version are you using?
There is an issue running zoneminder api under ubuntu 17.10.

**Comment by eXplOiD1** [comment]
Today when i come home from holidays i wrote you the needed Informations.

If you speak German we can speak German too

**Comment by DeadBoolean** [comment]
Deutsch ist in Ordnung.  ;-) 
Ich schau mal rein, wenn Du die Daten gesendet hast.

**Comment by eXplOiD1** [comment]
16.04.3 LTS (GNU/Linux 4.4.0-103-generic x86_64)
nodejs -v v6.12.2
php -v PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
und die Zoneminder version ist v1.30.4

**Comment by eXplOiD1** [comment]
gerne um das ganze zu vereinfachen können wir auch über ts3 reden wenn du möchtest.

**Comment by DeadBoolean** [comment]
Post bitte mal die error.log vom Apache (/var/log/apache2/error.log)
Ich habe leider kein TeamSpeak.

**Comment by eXplOiD1** [comment]
[Mon Dec 25 07:35:08.564558 2017] [mpm_prefork:notice] [pid 1895] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Dec 25 07:35:08.564593 2017] [core:notice] [pid 1895] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 25 13:00:16.337415 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.120266 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.196974 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.258858 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 17:48:02.168785 2017] [:error] [pid 63357] [client 192.168.3.1:60154] INF [Login successful for user "admin"], referer: http://exploid.ddnss.de/zm/index.php
[Mon Dec 25 18:08:30.188267 2017] [core:error] [pid 65363] [client 127.0.0.1:33312] AH00126: Invalid URI in request GET localhost/zm//index.php?username=admin&password=3mvkux2n&action=login&view=console HTTP/1.1
[Mon Dec 25 18:08:30.198453 2017] [core:error] [pid 63357] [client 127.0.0.1:33314] AH00126: Invalid URI in request GET localhost/zm//api/host/getVersion.json HTTP/1.1, referer: localhost
[Mon Dec 25 18:09:00.626320 2017] [core:error] [pid 17176] [client 127.0.0.1:33330] AH00126: Invalid URI in request GET localhost/zm//index.php?username=admin&password=3mvkux2n&action=login&view=console HTTP/1.1
[Mon Dec 25 18:09:00.633358 2017] [core:error] [pid 17178] [client 127.0.0.1:33332] AH00126: Invalid URI in request GET localhost/zm//api/host/getVersion.json HTTP/1.1, referer: localhost
[Mon Dec 25 18:09:02.753674 2017] [:error] [pid 1209] [client 192.168.3.1:42332] INF [Login successful for user "admin"]
[Mon Dec 25 18:09:03.380288 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380366 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380598 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380633 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497490 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497566 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497807 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497858 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost

**Comment by DeadBoolean** [comment]
Ich habe Deinen Post gelöscht. Da standen Deine Passwörter im Klartext drin
und der Eintrag ist für jedermann sichtbar. 
Schick mir das lieber mal an deadboolean@wedler-online.de oder mach die Benutzernamen und Passwörter unkenntlich.

**Comment by eXplOiD1** [comment]
[Mon Dec 25 07:35:08.564558 2017] [mpm_prefork:notice] [pid 1895] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Dec 25 07:35:08.564593 2017] [core:notice] [pid 1895] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 25 13:00:16.337415 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.120266 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.196974 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 13:00:17.258858 2017] [:error] [pid 47130] [client 109.91.121.170:38195] INF [Login successful for user "exploid"]
[Mon Dec 25 17:48:02.168785 2017] [:error] [pid 63357] [client 192.168.3.1:60154] INF [Login successful for user "----------"], referer: http://exploid.ddnss.de/zm/index.php
[Mon Dec 25 18:08:30.188267 2017] [core:error] [pid 65363] [client 127.0.0.1:33312] AH00126: Invalid URI in request GET localhost/zm//index.php?username=----------&password=----------&action=login&view=console HTTP/1.1
[Mon Dec 25 18:08:30.198453 2017] [core:error] [pid 63357] [client 127.0.0.1:33314] AH00126: Invalid URI in request GET localhost/zm//api/host/getVersion.json HTTP/1.1, referer: localhost
[Mon Dec 25 18:09:00.626320 2017] [core:error] [pid 17176] [client 127.0.0.1:33330] AH00126: Invalid URI in request GET localhost/zm//index.php?username=----------&password=----------&action=login&view=console HTTP/1.1
[Mon Dec 25 18:09:00.633358 2017] [core:error] [pid 17178] [client 127.0.0.1:33332] AH00126: Invalid URI in request GET localhost/zm//api/host/getVersion.json HTTP/1.1, referer: localhost
[Mon Dec 25 18:09:02.753674 2017] [:error] [pid 1209] [client 192.168.3.1:42332] INF [Login successful for user "----------"]
[Mon Dec 25 18:09:03.380288 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380366 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380598 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.380633 2017] [:error] [pid 47131] [client 192.168.3.1:42334] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497490 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497566 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497807 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/tmp/zmlogs/cake_error.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost
[Mon Dec 25 18:09:03.497858 2017] [:error] [pid 47130] [client 192.168.3.1:42336] PHP Warning:  file_put_contents(/var/log/zmerror.log) [<a href='http://php.net/function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in /usr/share/zoneminder/www/api/lib/Cake/Log/Engine/FileLog.php on line 142, referer: localhost

**Comment by DeadBoolean** [comment]
da ist ein "/" zu viel. (...localhost/zm//index.php...)
Falls Du im Adapter "localhost/zm/" eingegeben hast, lass das abschließende "/" mal weg. 
Und Du hast ein Zugriffsrechte-Problem. Probier mal:
`sudo chown www-data:www-data /usr/share/zoneminder -R`

**Comment by eXplOiD1** [comment]
jo geht jetzt das rechteproblem war es und ich hatte am ende noch ein / in der config danke :)

**Comment by DeadBoolean** [comment]
Super.
Gern geschehen.
