### ISSUE TITLE
Could you provide some information?

### ISSUE THREAD

**Issue by GermanBluefox** [DeadBoolean/ioBroker.zoneminder#7]
It is very interesting, what is that :)

**Comment by eXplOiD1** [comment]
@GermanBluefox da der Entwickler zur zeit wohl nicht erreichbar ist kann ich dir ein paar informationen geben.
Zoneminder ist eine Software für Video überwachung, [https://zoneminder.com/](url)
dieser Adapter ermöglicht es die Kamera Signale als Objekt darzustellen und auch den Alarm Status usw.
abzufragen.
ich benutze es selbst um mein Smarthome System automatisiert ein Kamerafenster öffnen zu lassen.

**Comment by GermanBluefox** [comment]
Thank you. :)
